---
apiVersion: v1
kind: Namespace
metadata:
  name: bavitoi-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bavitoi-strapi
  namespace: bavitoi-prod
  labels:
    project: bavitoi-blog
    app: bavitoi-strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bavitoi-strapi
  template:
    metadata:
      labels:
        app: bavitoi-strapi
    spec:
      containers:
        - name: bavitoi-strapi
          image: wurkata/bavitoi-strapi:0.32.3
          imagePullPolicy: IfNotPresent
          env:
            - name: PG_USER
              value: strapi-to
            - name: PG_PASSWORD
              value: secret
            - name: PG_DB
              value: blog
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bavitoi-strapi
  namespace: bavitoi-prod
  labels:
    app: bavitoi-strapi
spec:
  selector:
    app: bavitoi-strapi
  ports:
    - port: 80
      protocol: TCP
