---
apiVersion: v1
kind: Namespace
metadata:
  name: bavitoi-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-deepthought-pvc
  namespace: bavitoi-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deepthought
  namespace: bavitoi-prod
  labels:
    project: bavitoi-blog
    app: pg-deepthought
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-deepthought
  template:
    metadata:
      labels:
        app: pg-deepthought
    spec:
      containers:
        - name: pg-deepthought
          image: postgres:12.4-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: strapi-to
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_DB
              value: blog
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pg-deepthought-pvc
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: pg-deepthought
  namespace: bavitoi-prod
  labels:
    app: pg-deepthought
spec:
  selector:
    app: pg-deepthought
  ports:
    - port: 5432
      protocol: TCP
